# @grace.module grace.artifact_hygiene
# @grace.purpose Discover and clean derived artifact files so agent workflows do not leave repository state that pollutes semantic discovery or graph export.
# @grace.interfaces discover_artifact_paths(scope_root, *, cleanable_only=False)->tuple[Path,...]; discover_unignored_artifact_paths(scope_root)->tuple[Path,...]; clean_artifacts(scope_root, *, dry_run=False)->ArtifactCleanResult; is_ignored_artifact_dir_name(dir_name)->bool
# @grace.invariant Artifact hygiene remains derived-only and must never redefine inline GRACE annotations as a source of truth.
# @grace.invariant Cleaner behavior must stay deterministic across relative and absolute scope roots.
from __future__ import annotations

import fnmatch
import os
import shutil
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


LINT_ARTIFACT_PATTERNS = (
    "*.pyfrag",
    "*.plan.json",
    ".grace.tmp.json",
    ".grace_plan_*",
)
TEMP_CLEAN_PATTERNS = (
    ".grace.tmp.json",
    ".grace_plan_*",
    ".tmp_*.json",
    ".tmp_*.pyfrag",
)
SKIPPED_DIR_NAMES = {
    ".git",
    ".hg",
    ".svn",
    "__pycache__",
    ".venv",
    "venv",
    "node_modules",
    ".mypy_cache",
    ".pytest_cache",
    ".pytest-tmp",
    ".pytest-basetemp",
    ".pytest-basetemp-runs",
    ".pytest-basetemp-test",
    ".tmp_parser_tests",
    "build",
    "dist",
}


# @grace.anchor grace.artifact_hygiene.ArtifactCleanResult
# @grace.complexity 1
class ArtifactCleanResult(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    ok: Literal[True] = True
    root_path: Path
    dry_run: bool = False
    cleaned_paths: tuple[Path, ...] = Field(default_factory=tuple)
    failed_paths: tuple[Path, ...] = Field(default_factory=tuple)


# @grace.anchor grace.artifact_hygiene.discover_artifact_paths
# @grace.complexity 4
# @grace.links grace.artifact_hygiene.is_ignored_artifact_dir_name
def discover_artifact_paths(scope_root: str | Path, *, cleanable_only: bool = False) -> tuple[Path, ...]:
    root_path = Path(scope_root).expanduser().resolve()
    if root_path.is_file():
        root_path = root_path.parent

    patterns = TEMP_CLEAN_PATTERNS if cleanable_only else LINT_ARTIFACT_PATTERNS
    discovered_paths: list[Path] = []

    for current_root, dir_names, file_names in os.walk(root_path):
        root = Path(current_root)
        retained_dir_names: list[str] = []
        for dir_name in sorted(dir_names):
            if dir_name in SKIPPED_DIR_NAMES or dir_name.endswith(".egg-info"):
                continue
            if any(fnmatch.fnmatch(dir_name, pattern) for pattern in patterns):
                discovered_paths.append((root / dir_name).resolve())
                continue
            retained_dir_names.append(dir_name)
        dir_names[:] = retained_dir_names

        for file_name in sorted(file_names):
            if any(fnmatch.fnmatch(file_name, pattern) for pattern in patterns):
                discovered_paths.append((root / file_name).resolve())

    return tuple(sorted(dict.fromkeys(discovered_paths), key=str))


# @grace.anchor grace.artifact_hygiene.discover_unignored_artifact_paths
# @grace.complexity 5
# @grace.links grace.artifact_hygiene.discover_artifact_paths
def discover_unignored_artifact_paths(scope_root: str | Path) -> tuple[Path, ...]:
    root_path = Path(scope_root).expanduser().resolve()
    if root_path.is_file():
        root_path = root_path.parent

    ignore_root = _find_ignore_root(root_path)
    ignore_patterns = _load_ignore_patterns(ignore_root)

    unignored_paths: list[Path] = []
    for artifact_path in discover_artifact_paths(root_path, cleanable_only=False):
        if not _is_ignored_by_patterns(ignore_root, artifact_path, ignore_patterns):
            unignored_paths.append(artifact_path)

    return tuple(unignored_paths)


# @grace.anchor grace.artifact_hygiene.clean_artifacts
# @grace.complexity 5
# @grace.belief Cleanup should only remove deterministic temp artifacts generated by GRACE workflows, leaving committed example plans and replacement fragments untouched even when they are lint-visible as derived artifacts.
# @grace.links grace.artifact_hygiene.discover_artifact_paths
def clean_artifacts(scope_root: str | Path, *, dry_run: bool = False) -> ArtifactCleanResult:
    root_path = Path(scope_root).expanduser().resolve()
    if root_path.is_file():
        root_path = root_path.parent

    artifact_paths = discover_artifact_paths(root_path, cleanable_only=True)
    if dry_run:
        return ArtifactCleanResult(root_path=root_path, dry_run=True, cleaned_paths=artifact_paths)

    cleaned_paths: list[Path] = []
    failed_paths: list[Path] = []
    for artifact_path in artifact_paths:
        try:
            if artifact_path.is_dir():
                shutil.rmtree(artifact_path)
            else:
                artifact_path.unlink()
        except OSError:
            failed_paths.append(artifact_path)
        else:
            cleaned_paths.append(artifact_path)

    return ArtifactCleanResult(
        root_path=root_path,
        dry_run=False,
        cleaned_paths=tuple(cleaned_paths),
        failed_paths=tuple(failed_paths),
    )


# @grace.anchor grace.artifact_hygiene.is_ignored_artifact_dir_name
# @grace.complexity 1
def is_ignored_artifact_dir_name(dir_name: str) -> bool:
    return fnmatch.fnmatch(dir_name, ".grace_plan_*")


def _find_ignore_root(scope_root: Path) -> Path:
    for candidate in (scope_root, *scope_root.parents):
        if (candidate / ".gitignore").exists():
            return candidate
    return scope_root


def _load_ignore_patterns(ignore_root: Path) -> tuple[str, ...]:
    ignore_file = ignore_root / ".gitignore"
    if not ignore_file.exists():
        return ()
    patterns: list[str] = []
    for raw_line in ignore_file.read_text(encoding="utf-8").splitlines():
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        patterns.append(stripped)
    return tuple(patterns)


def _is_ignored_by_patterns(ignore_root: Path, artifact_path: Path, patterns: tuple[str, ...]) -> bool:
    relative_path = artifact_path.resolve().relative_to(ignore_root.resolve()).as_posix()
    name = artifact_path.name
    for pattern in patterns:
        normalized_pattern = pattern.replace("\\", "/")
        if normalized_pattern.endswith("/"):
            prefix = normalized_pattern.rstrip("/")
            if relative_path == prefix or relative_path.startswith(f"{prefix}/"):
                return True
            if name == prefix:
                return True
            continue
        if fnmatch.fnmatch(relative_path, normalized_pattern):
            return True
        if fnmatch.fnmatch(name, normalized_pattern):
            return True
    return False


__all__ = [
    "ArtifactCleanResult",
    "clean_artifacts",
    "discover_artifact_paths",
    "discover_unignored_artifact_paths",
    "is_ignored_artifact_dir_name",
]
